"""
UI Package for Retail Customer Intelligence Streamlit App.

Centralized design system with tokens, components, charts, and theme support.
"""

from .tokens import (
    LIGHT_TOKENS,
    DARK_TOKENS,
    SPACING,
    RADIUS,
    SHADOW,
    TYPOGRAPHY,
    LAYOUT,
    ColorTokens,
    SpacingTokens,
    RadiusTokens,
    ShadowTokens,
    TypographyTokens,
    LayoutTokens,
    generate_css_variables,
    get_theme_tokens,
    STATUS_COLORS,
    ACTION_COLORS,
    SEGMENT_PALETTE,
    PLOTLY_CONFIG,
    SEED,
)

from .theme import (
    get_current_theme,
    get_color_tokens,
    inject_global_css,
    get_status_color,
    get_action_color,
    get_segment_color,
    get_plotly_theme,
    apply_plotly_theme,
)

from .components import (
    render_kpi_card,
    render_kpi_row,
    render_science_card,
    render_status_chip,
    render_status_row,
    render_evidence_table,
    render_missing,
    render_empty_state,
    render_download_button,
    render_customer_selector,
    render_action_summary_table,
    render_page_hero,
    render_section_label,
    render_customer_header,
    render_customer_metric_row,
    render_formatted_dataframe,
    render_action_badge,
    render_segment_badge,
    responsive_columns,
    HERO_COPY,
    render_sidebar,
)

from .charts import (
    plot_missing,
    plot_histogram,
    plot_histogram_with_marginal,
    plot_horizontal_bar,
    plot_stacked_bar,
    plot_scatter,
    plot_scatter_with_quadrants,
    plot_heatmap,
    plot_segment_heatmap,
    plot_line,
    plot_dual_axis_line_bar,
    plot_retention_matrix,
    plot_decay_curve,
    plot_uncertainty_band,
    plot_pca_scatter,
    plot_concentration_curve,
    plot_action_allocation,
    plot_clv_by_segment,
    plot_decision_scatter,
    plot_priority_distribution,
    plot_expected_value_by_action,
    plot_clv_vs_churn_by_action,
)

__all__ = [
    # Tokens
    "LIGHT_TOKENS",
    "DARK_TOKENS",
    "SPACING",
    "RADIUS",
    "SHADOW",
    "TYPOGRAPHY",
    "LAYOUT",
    "ColorTokens",
    "SpacingTokens",
    "RadiusTokens",
    "ShadowTokens",
    "TypographyTokens",
    "LayoutTokens",
    "generate_css_variables",
    "get_theme_tokens",
    "STATUS_COLORS",
    "ACTION_COLORS",
    "SEGMENT_PALETTE",
    "PLOTLY_CONFIG",
    "SEED",
    # Theme
    "get_current_theme",
    "get_color_tokens",
    "inject_global_css",
    "get_status_color",
    "get_action_color",
    "get_segment_color",
    "get_plotly_theme",
    "apply_plotly_theme",
    # Components
    "render_kpi_card",
    "render_kpi_row",
    "render_science_card",
    "render_status_chip",
    "render_status_row",
    "render_evidence_table",
    "render_missing",
    "render_empty_state",
    "render_download_button",
    "render_customer_selector",
    "render_action_summary_table",
    "render_page_hero",
    "render_section_label",
    "render_customer_header",
    "render_customer_metric_row",
    "render_formatted_dataframe",
    "render_action_badge",
    "render_segment_badge",
    "responsive_columns",
    "HERO_COPY",
    # Charts
    "plot_missing",
    "plot_histogram",
    "plot_histogram_with_marginal",
    "plot_horizontal_bar",
    "plot_stacked_bar",
    "plot_scatter",
    "plot_scatter_with_quadrants",
    "plot_heatmap",
    "plot_segment_heatmap",
    "plot_line",
    "plot_dual_axis_line_bar",
    "plot_retention_matrix",
    "plot_decay_curve",
    "plot_uncertainty_band",
    "plot_pca_scatter",
    "plot_concentration_curve",
    "plot_action_allocation",
    "plot_clv_by_segment",
    "plot_decision_scatter",
    "plot_priority_distribution",
    "plot_expected_value_by_action",
    "plot_clv_vs_churn_by_action",
]